config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "instruments#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'instruments/posts', to: 'instruments#posts', as: :posts

  resources :instruments do
    resources :reviews, only: %i[create]
    resources :bookings, only: %i[create]
  end

  resources :bookings, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :instrument
  has_many :reviews
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 450 }
  validates :price, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name, against: :name, using: { tsearch: { prefix: true } }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  # belongs_to :instrument, through: :booking
  # belongs_to :user, through: :booking

  validates :rating, presence: true, inclusion: { in: [1, 2, 3, 4, 5] }
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  has_many :bookings
  has_many :instruments, through: :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :address, :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name address photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name address photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @user = current_user
    @booking = Booking.new(params_booking)
    @booking.user = @user
    @instrument = Instrument.find(params[:instrument_id])
    @booking.instrument = @instrument
    if @booking.save
      redirect_to bookings_path
    else
      redirect_to instrument_path(@instrument), status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @user = @booking.user
    @instrument = @booking.instrument
  end

  def index
    @bookings = Booking.where(user: current_user)
  end

  private

  def params_booking
    params.require(:booking).permit(:start, :end, :instrument_id)
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      @instruments = Instrument.search_by_name(params[:query])
    else
      @instruments = Instrument.all
    end
  end

  def posts
    @posts = Instrument.where(user: current_user)
  end

  def show
    @instrument = Instrument.find(params[:id])
    @marker = {
        lat: @instrument.latitude,
        lng: @instrument.longitude
    }
    @booking = Booking.new
    @review = Review.new

    if @instrument.reviews.nil?
      @reviews = []
    else
      @reviews = @instrument.reviews.order(created_at: :desc)
    end
  end

  def new
    @instrument = Instrument.new
  end

  def create
    @user = current_user
    @instrument = Instrument.new(params_instrument)
    @instrument.user = @user
    @instrument.address = current_user.address

    if @instrument.save
      # redirect_to instrument_path(@instrument)
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def params_instrument
    params.require(:instrument).permit(:name, :description, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(params_review)
    @instrument = Instrument.find(params[:instrument_id])
    @review.booking = current_user.bookings.find_by(instrument_id: params[:instrument_id])

    if @review.save
      redirect_to instrument_path(@instrument)
    else
      redirect_to instrument_path(@instrument), status: :unprocessable_entity,
                                                notice: "Book this instrument before you can leave a review"
    end
  end

  private

  def params_review
    params.require(:review).permit(:rating, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<%= render "shared/navbar" %>
<p class="title mt-4">Listing your bookings</h1>


<div class="article-container">
  <br>

  <div class="cards-container">
    <% @bookings.each do |booking| %>

        <div class="booking-product-card">
        <% if booking.instrument.photo.attached? %>
          <div class="img-bg" style="background-image:url('<%= cl_image_path booking.instrument.photo.key, height: 300, crop: :fill %>')";></div>
        <% else %>
          <div class="img-bg-none"><p>No Image</p></div>
        <% end %>
          <div class="product-content">
            <p><%= booking.instrument.name %></p>
            <p>Duration: <%= booking.start %> | <%= booking.end %></p>
            <p>Owner: <%= booking.user.first_name %></p>
            <p>Price: Rs<%= booking.instrument.price %> / Day</p>
            <p class="mt-3"><%= link_to "Leave a review", instrument_path(booking.instrument) , class: "leave-review-btn" %></p>
          </div>
        </div>

    <% end %>
  </div>
<br><br><br>

</div>

app/views/instruments/index.html.erb
<%= render "shared/navbar" %>
<%= render "shared/banner" %><br><br>
<%= render "shared/search_form" %>
<br><br>

<p class="title">Music Instruments around the world</p>
<div class="article-container">
  <br>

  <div class="cards-container">
    <% @instruments.each do |instrument| %>
      <div class="product-card">
        <%= link_to instrument_path(instrument), :action => 'go' do %>
        <% if instrument.photo.attached? %>
          <div class="img-bg" style="background-image:url('<%= cl_image_path instrument.photo.key %>')";></div>
        <% else %>
          <div class="img-bg-none"><p>No Image</p></div>
        <% end %>
          <div class="product-content">
            <div class="content-top">
              <p><%= instrument.name %></p>
              <p><i class="fa-solid fa-star"></i> <%= rand(0..5) %></p>
            </div>
            <p><strong>Price:</strong> Rs<%= instrument.price %> / Day</p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<br><br><br>

</div>

<article>
  <div class="article-text">
    <h3>A place to find your instruments</h3>
    <p>We are slowed down sound and light waves, a walking bundle of frequencies tuned into the cosmos. We are souls dressed up in sacred biochemical garments and our bodies are the instruments through which our souls play their music.</p>
    <br>
    <p><%= link_to "Browse our range" %></p>
  </div>
</article>
<br><br>
<p class="title-footer">We work with some of the world's leading companies</p>
<footer>
  <p><i class="fa-brands fa-slack"></i>  Slack</p>
  <p><i class="fa-brands fa-square-facebook"></i>  Facebook</p>
  <p><i class="fa-brands fa-twitter"></i>  Twitter</p>
</footer>
<br>

app/views/instruments/new.html.erb
<div class="container-form">
<br>
<div class="form-side">
<p><%= link_to "< Back to home", root_path %></p>
<h2>Publish your offer</h2>

<div class="container mt-4">
  <%= simple_form_for(@instrument) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Add new offer", class: "btn btn-primary" %>
  <% end %>
</div>
  </div>
  <div class="img-side" style="background-image:url(https://images.unsplash.com/photo-1542357411977-726a8931ee8b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjR8fHNlbGxpbmclMjBpbnN0cnVtZW50fGVufDB8MXwwfHw%3D&auto=format&fit=crop&w=500&q=60);"></div>

</div>

app/views/instruments/posts.html.erb
<%= render 'shared/navbar' %>
<div class="post">
  <div class="container">
    <br><br>
    <h1 class='text-center mb-4'>My Posts</h1>
    <div class="cards-container">
    <% @posts.each do |post| %>

    <div class="product-card" style="height: 310px;">
    <% if post.photo.attached? %>
      <div class="img-bg" style="background-image:url('<%= cl_image_path post.photo.key, height: 300, crop: :fill %>')";></div>
    <% else %>
      <div class="img-bg-none"><p>No Image</p></div>
    <% end %>
      <div class="product-content">
        <p><%= post.name %></p>
        <p><strong>Posted on:</strong> <%= post.created_at %></p>
        <p><strong>Price:</strong> Rs<%= post.price %> / Day</p>
      </div>
    </div>

    <% end %>
    </div>
  </div>
</div>

app/views/instruments/show.html.erb
<%= render "shared/navbar" %>
<div class="container mt-4">

  <div class="container-show">
    <section class="main-card mb-4">
      <div class="card-content">
          <div class="content-left">
            <% if @instrument.photo.attached? %>
              <%= cl_image_tag @instrument.photo.key, class: "full-img" %>
            <% else %>
              <div class="full-img show-img-bg-none"><p>No Image</p></div>
            <% end %>
          </div>
          <div class="content-right">
              <h2 class="strong"><%= @instrument.name %></h2>
              <p><%= @instrument.description %></p>
              <p>Rs <%= @instrument.price %> / day</p>
              <p class="strong">Owner: <%= @instrument.user.first_name %> <%= @instrument.user.last_name %></p>
              <p class='strong'>Location: <%= @instrument.user.address %></p>
              <p class='strong'>Contact: <%= @instrument.user.email %></p>
              <button style='width: 100%' type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">BOOK</button>
          </div>
      </div>
    </section>
    <div style="width: 40%; height: 635px;"
        data-controller="map"
        data-map-marker-value="<%= @marker.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

  <h3 class="my-4" style="text-align:center;">Reviews (<%= @reviews.count %>)</h3>

  <% if @instrument.bookings.any? { |booking| booking.user == current_user } %>
    <div class="reviews-form">
      <%= simple_form_for [@instrument, @review] do |f| %>
      <%= f.input :comment %>
      <%= f.input :rating %>
      <%= f.submit "Add review", class: "btn btn-primary" %>
      <% end %>
    </div>
  <% end %>

  <br><br><br>

  <% @reviews.each do |review| %>
    <div class="review-container">
      <p style="text-align:center;">
        <%= '⭐'*review.rating %>
      </p>

      <p style="text-align:center;">“<%= review.comment %>”</p>
      <p class="user"> - <%= review.booking.user.first_name %> <%= review.booking.user.last_name %>
        <span>
          <% if review.booking.user.photo.attached? %>
            <%= cl_image_tag review.booking.user.photo.key, class: "avatar" %>
          <% else %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar" %>
          <% end %>
        </span>
      </p>
    </div>
    <br><br>
  <% end %>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@instrument, @booking] do |f| %>
          <%= f.input :start %>
          <%= f.input :end %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@instrument, @booking] do |f| %>
          <%= f.input :start %>
          <%= f.input :end %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musifun</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">

  </head>

  <body>
    <%= yield %>
    <%= render "shared/flashes" %>
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </body>

</html>

app/views/shared/_banner.html.erb
<div id="banner">
  <p class="title-banner">Making the world sound better</p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
   <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Thanks for your visits
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "Musifun", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "My Posts", posts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Publish an offer", new_instrument_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">


          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>


            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit my profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete},
              class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
<div class="container">
  <%= form_with url: instruments_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find an instrument"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
</div>